version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - "8080:80"  # Map port 8080 on the host to port 80 in the container
    environment:
      WORDPRESS_DB_HOST: db  # Hostname of the database service
      WORDPRESS_DB_USER: wp_user  # Username for the database
      WORDPRESS_DB_PASSWORD: wp_password  # Password for the database
      WORDPRESS_DB_NAME: wp_database  # Database name
    depends_on:
      - db  # Ensure the db service is started before wordpress

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password  # Root password for MySQL
      MYSQL_DATABASE: wp_database  # Create this database on startup
      MYSQL_USER: wp_user  # Create this user
      MYSQL_PASSWORD: wp_password  # Password for the new user
    volumes:
      - db_data:/var/lib/mysql  # Persist MySQL data

volumes:
  db_data:  # Named volume for persistent MySQL data
